INSERT INTO garden (
        name,
        image,
        origin,
        category,
        ideal_light,
        ideal_watering,
        last_water,
        is_healthy,
        email,
        user_id,
        demo_plant,
        actions,
        skip_count,
        skip_history
    )
VALUES (
        'Peace Lily',
        '20181128081621_file_5bfef795f08dd.webp',
        'South Africa',
        'Tropical',
        'Indirect',
        'Keep soil moist, water when half dry',
        '2022/08/25',
        1,
        'test@fake.com',
        0,
        1,
        '[{ "action": "Watered", "date": "2022/08/25", "action_number": 1}, { "action": "Watered", "date": "2022/08/30", "action_number": 2}]',
        0,
        '[1,1,1]'
    ),
    (
        'Fern',
        'fernTest.jpeg',
        'UK',
        'Tropical',
        'Indirect',
        'Keep soil moist, water when half dry',
        '2022/08/30',
        0,
        'test@fake.com',
        0,
        1,
        '[{ "action": "Skipped", "date": "2022/08/25", "action_number": 1}, { "action": "Skipped", "date": "2022/08/30", "action_number": 2}]',
        0,
        '[2,2,2]'
    ),
    (
        'Snake Plant',
        'black-gold-snake-plant_x560.progressive.webp',
        'West Africa',
        'Tropical',
        'Shaded',
        'Keep soil dry, water when dry',
        '2022/08/25',
        1,
        'test@fake.com',
        0,
        1,
        '[{ "action": "Updated", "date": "2022/08/25", "action_number": 1}, { "action": "Updated", "date": "2022/08/30", "action_number": 2}]',
        0,
        '[3,3,3]'
    );
INSERT INTO users (name, password, email)
VALUES ('User1', 'a', 'test@fake.com'),
    ('User2', 'b', 'test@fake.com');